name: Deploy Dev PR

on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        description: 'Select network'
        default: 'Testnet'
        options:
          - 'Both'
          - 'Testnet'
          - 'Mainnet'
      build_all:
        type: boolean
        description: 'Build all'
        default: true
      deploy_web:
        type: boolean
        description: 'Deploy web'
        default: false
      build_android:
        type: boolean
        description: 'Build Android'
        default: false
      build_windows:
        type: boolean
        description: 'Build Windows'
        default: false
      build_macos:
        type: boolean
        description: 'Build macOS'
        default: false
      build_linux:
        type: boolean
        description: 'Build Linux'
        default: false

jobs:

  # Merge all 'deploy.dev' PRs to master branch
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Log Job Run
        run: echo "Job was run at $(date)"

  # Deploy test & pre sites
  deploy-pre:
    needs: merge
    if: ${{ github.event.inputs.deploy_web == true && github.event.inputs.network == 'Mainnet' && github.event.inputs.network == 'Both' }}
    runs-on: gui
    steps:
      - name: Log Job Run
        run: echo "Job was run at $(date)"

  deploy-test:
    needs: merge
    if: ${{ github.event.inputs.deploy_web == true && github.event.inputs.network == 'Testnet' && github.event.inputs.network == 'Both' }}
    runs-on: gui
    steps:
      - name: Log Job Run
        run: echo "Job was run at $(date)"

  # Build & Deploy proxy services
  build-proxy:
    needs: merge
    if: ${{ github.event.inputs.deploy_proxy == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Log Job Run
        run: echo "Job was run at $(date)"

  deploy-proxy:
    needs: build-proxy
    if: ${{ github.event.inputs.network == 'Mainnet' && github.event.inputs.network == 'Both' }}
    runs-on: proxy.test
    steps:
      - name: Log Job Run
        run: echo "Job was run at $(date)"

  deploy-proxy-test:
    needs: build-proxy
    if: ${{ github.event.inputs.network == 'Testnet' && github.event.inputs.network == 'Both' }}
    runs-on: proxy.test
    steps:
      - name: Log Job Run
        run: echo "Job was run at $(date)"
  
  # Build applications
  build-app-macos:
    needs: merge
    if: ${{ github.event.inputs.build_macos == true }}
    runs-on: macos-latest
    steps:
      - name: Log Job Run
        run: echo "Job was run at $(date)"
        
  build-app-unix:
    needs: merge
    if: ${{ github.event.inputs.build_linux == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Log Job Run
        run: echo "Job was run at $(date)"
    
  build-app-windows:
    needs: merge
    if: ${{ github.event.inputs.build_windows == true }}
    runs-on: windows-latest
    steps:
      - name: Log Job Run
        run: echo "Job was run at $(date)"

  build-app-android:
    needs: merge
    if: ${{ github.event.inputs.build_android == true }}
    runs-on: ubuntu-20.04
    steps:
      - name: Log Job Run
        run: echo "Job was run at $(date)"

  build-app-android-gf:
    needs: merge
    if: ${{ github.event.inputs.build_android == true }}
    runs-on: ubuntu-20.04
    steps:
      - name: Log Job Run
        run: echo "Job was run at $(date)"

  deploy-app-binaries:
    needs: [ build-app-macos, build-app-unix, build-app-windows, build-app-android, build-app-android-gf ]
    if: ${{ always() || github.event.inputs.build_android == true || github.event.inputs.build_windows == true || github.event.inputs.build_linux == true || github.event.inputs.build_macos == true }}
    runs-on: dev.pocketnet.app
    steps:
      - name: Log Job Run
        run: echo "Job was run at $(date)"
