name: Deploy Dev PR

on:
  workflow_dispatch:

jobs:

  # Merge all 'deploy.dev' PRs to master branch
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0 # We need a complete history for merging branches
      - uses: andyoknen/combine-pull-requests@v1
        with:
          label: deploy.dev
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive merged repo
        run: |
          mkdir -p /tmp/repo
          rsync -ah --exclude={'.git','.gitignore','.github','node_modules','.well-known'} ./ /tmp/repo/
          cd /tmp/repo
          tar czf /tmp/repo.tgz ./
      - name: Upload artifact repo.tgz
        uses: actions/upload-artifact@v1
        with:
          name: repo.tgz
          path: /tmp/repo.tgz
      - name: Save artifact head.txt
        uses: actions/upload-artifact@v1
        with:
          name: head
          path: ./head.txt

  build-app-unix:
    needs: merge
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: repo.tgz
      - name: Unpack artifact
        run: tar xzf repo.tgz
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Prepare building
        run: |
          npm run fix:canvas
          npm run dev:bastyon
      - name: Building
        run: |
          npm run distl
          ls -lh ./dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: unix
          path: |
            ./dist/BastyonSetup.deb
            ./dist/Bastyon.AppImage
    
  build-app-windows:
    needs: merge
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: repo.tgz
      - name: Unpack artifact
        run: tar xzf repo.tgz
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Prepare building
        run: |
          npm run fix:canvas
          npm run dev:bastyon
      - name: Building
        run: |
          npm run dist
          ls .\dist\
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ./dist/BastyonSetup.exe

  build-app-android:
    needs: merge
    runs-on: ubuntu-20.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: repo.tgz
      - name: Unpack artifact
        run: tar xzf repo.tgz
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Cordova
        run: |
          npm i -g cordova@10
          cordova --version
      - name: Prepare building
        run: |
          npm run fix:canvas
          npm run minimize:cordova
          cd ./cordova
          npm i
      - name: Prepare configuration
        run: |
          cd ./cordova
          echo "${{ secrets.ANDROID_SECRET_KEY }}" | base64 -d > cert.keystore
          echo "${{ secrets.ANDROID_BUILD_CONF }}" | base64 -d > build.json
          echo "${{ secrets.ANDROID_FIREBASE_CONF }}" | base64 -d > google-services.json
          ls -l cert.keystore
          ls -l build.json
      - name: Fixing Android Build Tool Issue
        run: |
            cd $ANDROID_HOME/build-tools/33.0.0
            mv d8 dx
            cd lib
            mv d8.jar dx.jar
      - name: Configure Cordova Plugins
        run: |
          cd ./cordova
          npm run android-add
      - name: Building
        run: |
          cd ./cordova
          npm run android-build
      - name: Rename apk binary
        run: |
          cd ./cordova/platforms/android/app/build/outputs/apk/release
          ls -lh
          mv app-release.apk Bastyon.apk
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: ./cordova/platforms/android/app/build/outputs/apk/release/Bastyon.apk