name: Deploy Proxy

on:
  workflow_dispatch:
    inputs:
      proxy1:
        type: boolean
        description: Deploy to proxy 1
      proxy2:
        type: boolean
        description: Deploy to proxy 2
      proxy3:
        type: boolean
        description: Deploy to proxy 3
      proxy6:
        type: boolean
        description: Deploy to proxy 6

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner: [ 1, 2, 3, 6 ]
        skip: ${{ github.event.inputs }}
    steps:
      - name: Output variables (debug)
        run: |
          echo '${{ matrix.runner }}'
          echo '${{ matrix.skip }}'
