name: Deploy Dev PR

on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        description: 'Select network'
        default: 'Testnet'
        options:
          - 'Testnet'
          - 'Mainnet'
      build_all:
        type: boolean
        description: 'Build all'
        default: true
      build_android:
        type: boolean
        description: 'Build Android'
        default: true
      build_windows:
        type: boolean
        description: 'Build Windows'
        default: true
      build_macos:
        type: boolean
        description: 'Build macOS'
        default: true
      build_linux:
        type: boolean
        description: 'Build Linux'
        default: true

jobs:
  # Merge all 'deploy.dev' PRs to master branch
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0 # We need a complete history for merging branches
      - uses: andyoknen/combine-pull-requests@v1
        with:
          label: deploy.dev
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive merged repo
        run: |
          mkdir -p /tmp/repo
          rsync -ah --exclude={'.git','.gitignore','.github','node_modules','.well-known'} ./ /tmp/repo/
          cd /tmp/repo
          tar czf /tmp/repo.tgz ./
      - name: Upload artifact repo.tgz
        uses: actions/upload-artifact@v3
        with:
          name: repo.tgz
          path: /tmp/repo.tgz
      - name: Save artifact head.txt
        uses: actions/upload-artifact@v3
        with:
          name: head
          path: ./head.txt
