name: Deploy Dev PR

on:
  workflow_dispatch:

jobs:

  # Merge all 'deploy.dev' PRs to master branch
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0 # We need a complete history for merging branches

  # Deploy test & pre sites
  deploy-pre:
    needs: merge
    runs-on: gui
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: repo.tgz
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Prepare
        run: |
          tar xzf repo.tgz
          rm -rf repo.tgz
          npm i
          npm run minimize:bastyon -- -sha=${{ github.sha }} -run=${{ github.run_number }}${{ github.run_attempt }}
      - name: Create deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          ref: '${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}'
          token: '${{ github.token }}'
          environment-url: 'https://pre.pocketnet.app/'
          environment: 'dev'
      - name: Copy to dest dir
        run: echo 'dummy'
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          ref: '${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}'
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          ref: '${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}'
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'failure'
