name: Lookup and update Proxy16 hosts

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install JQ package
        run: sudo apt-get install jq

      - name: Create a branch
        run: git checkout -b proxy16/update-hosts

      - name: Run the lookup script
        run: |
          cd proxy16
          chmod +x service/lookup.sh
          service/lookup.sh

      - name: Commit hosts file
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: proxy16/update-hosts
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Update Proxy16 video servers'
          add: proxy16/peertube-servers.json
          fetch: false

      - name: Create PR
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: proxy16/update-hosts
          target_branch: master-shpiga
          title: Update Proxy16 video servers
          template: .github/PULL_REQUEST_TEMPLATE.md
          reviewer: shpingalet007
          assignee: shpingalet007
          label: enhancement
          draft: true